export type FILTER_ACTIONS_TYPES = keyof typeof FILTER_ACTIONS;

export const FILTER_ACTIONS = {
    SHOW_SELECTED: 'SHOW_SELECTED',
    SHOW_UNSELECTED: 'SHOW_UNSELECTED',
    SHOW_MATCHES: 'SHOW_MATCHES',
    SHOW_GENERATED: 'SHOW_GENERATED',
    SHOW_VALUE_MAPPINGS: 'SHOW_VALUE_MAPPINGS',
    SHOW_OBJECT_MAPPINGS: 'SHOW_OBJECT_MAPPINGS',
};
