import React, { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import ReactDOM from "react-dom";
import { Helmet } from "react-helmet";
import {
    BreadcrumbList,
    OverviewItem,
    OverviewItemActions,
    OverviewItemDepiction,
    OverviewItemDescription,
    OverviewItemLine,
    BreadcrumbItemProps,
} from "@eccenca/gui-elements";
import { ItemDepiction } from "../ItemDepiction/ItemDepiction";
import { routerOp } from "@ducks/router";
import { APPLICATION_CORPORATION_NAME, APPLICATION_SUITE_NAME } from "../../../constants/base";
import { fetchBreadcrumbs } from "./breadcrumbsHelper";
import { AppDispatch } from "store/configureStore";

interface IPageHeaderContentBasicProps extends React.HTMLAttributes<HTMLDivElement> {
    /** Optional type of the page item. Can be an ItemType. */
    type?: string;
    /** Optional plugin ID of the page item. */
    pluginId?: string;
    alternateDepiction?: string;
    breadcrumbs?: BreadcrumbItemProps[];
    breadcrumbsExtensions?: BreadcrumbItemProps[]; // breadcrumbs additional to the autogenerated ones
    autogenerateBreadcrumbs?: boolean;
    pageTitle?: string;
    autogeneratePageTitle?: boolean;
    actionsMenu?: React.JSX.Element;
}

/*
interface IPageHeaderContentAutogenerateBreadcrumbsProps extends IPageHeaderContentBasicProps {
    autogenerateBreadcrumbs: true;
    breadcrumbs?: never;
}

interface IPageHeaderContentAutogeneratePageTitleProps extends IPageHeaderContentAutogenerateBreadcrumbsProps {
    autogeneratePageTitle: true;
    pageTitle?: never;
}

type TPageHeader = IPageHeaderContentBasicProps &
    IPageHeaderContentAutogenerateBreadcrumbsProps &
    IPageHeaderContentAutogeneratePageTitleProps;
*/

export const APP_VIEWHEADER_ID = "diapp__viewheader";

// Header element that uses portal function to get rendered in one special place regardless from where it is used
export function PageHeader({ autogenerateBreadcrumbs = false, ...headerProps }: IPageHeaderContentBasicProps) {
    const PageHeader = autogenerateBreadcrumbs ? PageHeaderContentWithBreadCrumbs : PageHeaderContent;

    return (
        <PageHeaderPortal>
            <PageHeader {...headerProps} />
        </PageHeaderPortal>
    );
}

function PageHeaderPortal({ children }: any) {
    const [portalEnabled, setPortalEnabled] = useState(false);
    const portalTarget = document.getElementById(APP_VIEWHEADER_ID);

    useEffect(() => {
        if (portalTarget && !portalEnabled) {
            portalTarget.innerHTML = "";
            setPortalEnabled(true);
        }
    });

    return portalEnabled && portalTarget ? ReactDOM.createPortal(<>{children}</>, portalTarget) : <></>;
}

function PageHeaderContent({
    type,
    pluginId,
    breadcrumbs,
    breadcrumbsExtensions,
    pageTitle,
    autogeneratePageTitle = false,
    actionsMenu,
}: IPageHeaderContentBasicProps) {
    const dispatch = useDispatch<AppDispatch>();

    const handleBreadcrumbItemClick = React.useCallback((itemUrl, e) => {
        e.preventDefault();
        if (itemUrl) {
            dispatch(routerOp.goToPage(itemUrl, {}));
        }
    }, []);

    const generatedPageTitle =
        autogeneratePageTitle && breadcrumbs && breadcrumbs.length > 0
            ? (breadcrumbs[breadcrumbs.length - 1].text ?? "").toString()
            : "";

    const renderWindowTitle = () => {
        const typeinfo = !!type ? `(${type})` : "";
        const position =
            !!breadcrumbs && breadcrumbs.length > 1
                ? "at " +
                  breadcrumbs
                      .slice(0, breadcrumbs.length - 1)
                      .map((o) => o.text)
                      .join(" / ")
                : "";
        const brandingSuffix =
            APPLICATION_CORPORATION_NAME() || APPLICATION_SUITE_NAME()
                ? ` — ${APPLICATION_CORPORATION_NAME()} ${APPLICATION_SUITE_NAME()}`
                : "";

        return `${pageTitle || generatedPageTitle} ${typeinfo} ${position}${brandingSuffix}`;
    };

    const displayedTitle = pageTitle || generatedPageTitle;
    // single-row header line: the page title is the trail's current (last) item, never a link.
    // `BreadcrumbList` renders the last item in the "current page" treatment automatically.
    const allBreadcrumbs = (breadcrumbs ?? []).concat(breadcrumbsExtensions ?? []);
    const trailWithCurrentPage =
        displayedTitle &&
        (allBreadcrumbs.length === 0 ||
            (allBreadcrumbs[allBreadcrumbs.length - 1].text ?? "").toString() !== displayedTitle)
            ? allBreadcrumbs.concat([{ text: displayedTitle }])
            : allBreadcrumbs;

    return (
        <>
            <Helmet title={renderWindowTitle()} />
            <OverviewItem>
                {!!type && (
                    <OverviewItemDepiction data-test-id="page-header-depiction">
                        <ItemDepiction itemType={type} pluginId={pluginId} size={{ small: true }} />
                    </OverviewItemDepiction>
                )}
                <OverviewItemDescription>
                    {trailWithCurrentPage.length > 0 && (
                        <OverviewItemLine>
                            {/* keep an h1 for the document outline; visually the current
                                breadcrumb item represents the page title */}
                            <h1 className="sr-only">{displayedTitle}</h1>
                            <BreadcrumbList items={trailWithCurrentPage} onItemClick={handleBreadcrumbItemClick} />
                        </OverviewItemLine>
                    )}
                </OverviewItemDescription>
                {!!actionsMenu && <OverviewItemActions>{actionsMenu}</OverviewItemActions>}
            </OverviewItem>
        </>
    );
}

const PageHeaderContentWithBreadCrumbs = fetchBreadcrumbs(PageHeaderContent);

// Custom hook to update single properties of the element
export function usePageHeader({ ...propsHeader }: IPageHeaderContentBasicProps) {
    const [pageHeaderProps, setPageHeaderProps] = useState<IPageHeaderContentBasicProps>({ ...propsHeader });

    const updatePageHeader = (propsUpdate: IPageHeaderContentBasicProps) => {
        setPageHeaderProps({ ...pageHeaderProps, ...propsUpdate });
    };

    const pageHeader = <PageHeader {...pageHeaderProps} />;
    return {
        pageHeader,
        updateType: (itemType: string, pluginId?: string) => {
            updatePageHeader({ type: itemType, pluginId });
        },
        updatePageTitle: (update) => {
            updatePageHeader({ pageTitle: update, autogeneratePageTitle: false });
        },
        updateBreadcrumbs: (update) => {
            updatePageHeader({ breadcrumbs: update, autogenerateBreadcrumbs: false });
        },
        updateBreadcrumbsExtensions: (update) => {
            updatePageHeader({ breadcrumbsExtensions: update, autogenerateBreadcrumbs: true });
        },
        updateActionsMenu: (update: React.JSX.Element) => {
            updatePageHeader({ actionsMenu: update });
        },
        updatePageHeader,
    } as const;
}
