export const FETCH_SEARCH_RESUTLS = "global/FETCH_SEARCH_RESULTS";
export const SEARCH_RESUTLS_SUCCESS = "global/SEARCH_RESULTS_SUCCESS";
export const SEARCH_RESUTLS_FAILURE = "global/SEARCH_RESULTS_FAILURE";

export const CHANGE_SEARCH_STRING = "global/CHANGE_SEARCH_STRING";
export const CHANGE_LANGUAGE = "global/CHANGE_LANGUAGE";
export const LOGIN_SUCCESS = "global/LOGIN_SUCCESS";
export const LOG_OUT = "global/LOG_OUT";
