package org.silkframework.rule

import org.silkframework.config.{Prefixes, Task}
import org.silkframework.dataset.{DataSource, Dataset, DatasetSpec}
import org.silkframework.entity.{Entity, EntitySchema}
import org.silkframework.entity.paths.{TypedPath, UntypedPath}
import org.silkframework.execution.EntityHolder
import org.silkframework.execution.local.{EmptyEntityTable, GenericEntityTable}
import org.silkframework.rule.execution.{TransformReport, TransformReportBuilder}
import org.silkframework.rule.execution.local.TransformedEntities
import org.silkframework.runtime.activity.{ActivityMonitor, UserContext}
import org.silkframework.runtime.iterator.CloseableIterator
import org.silkframework.runtime.plugin.{PluginContext, TaskResolver}
import org.silkframework.runtime.validation.BadUserInputException
import org.silkframework.util.Uri

import scala.collection.mutable

/**
  * A data source that transforms all entities using a provided transformation.
  *
  * @param source        The data source for retrieving the source entities.
  * @param transformRule The transformation
  */
class TransformedDataSource(source: DataSource, inputSchema: EntitySchema, transformRule: TransformRule, task: Task[TransformSpec]) extends DataSource {
  /**
    * Retrieves known generated types in this source.
    *
    * @param limit Restricts the number of types to be retrieved. No effect on this data source.
    */
  override def retrieveTypes(limit: Option[Int] = None)
                            (implicit userContext: UserContext, prefixes: Prefixes): Iterable[(String, Double)] = {
    for(TypeMapping(_, typeUri, _) <- transformRule.rules.typeRules) yield {
      (typeUri.toString, 1.0)
    }
  }

  /**
    * Retrieves all paths generated by this source.
    *
    * @param t The entity type for which paths shall be retrieved. No effect on this data source.
    * @param depth Only retrieve paths up to a certain length. No effect on this data source as all paths are of length one.
    * @param limit Restricts the number of paths to be retrieved. No effect on this data source.
    */
  override def retrievePaths(t: Uri, depth: Int = 1, limit: Option[Int] = None)
                            (implicit userContext: UserContext, prefixes: Prefixes): IndexedSeq[TypedPath] = {
    transformRule.rules.allRules.flatMap(_.target).map(_.asTypedPath()).distinct.toIndexedSeq
  }

  /**
    * Retrieves entities from this source which satisfy a specific entity schema.
    *
    * @param entitySchema The entity schema
    * @param limit        Limits the maximum number of retrieved entities
    * @return A Traversable over the entities. The evaluation of the Traversable may be non-strict.
    */
  override def retrieve(entitySchema: EntitySchema, limit: Option[Int])
                       (implicit context: PluginContext): EntityHolder = {
    implicit val prefixes: Prefixes = context.prefixes
    val rules = rulesForSubPath(entitySchema.subPath)
    // The limit bounds the whole result. Each rule still gets the full limit, so that a rule yielding fewer
    // entities than its share does not reduce the total.
    // Each rule's source is opened only when the previous one is exhausted, and whatever was opened is closed
    val openedIterators = mutable.Buffer[CloseableIterator[Entity]]()
    val entities = rules.iterator.flatMap { case (ruleInputSchema, rule) =>
      val iterator = transformedEntities(ruleInputSchema, rule, entitySchema, limit)
      openedIterators += iterator
      iterator
    }
    val allEntities = CloseableIterator(entities, () => openedIterators.foreach(_.close()))
    GenericEntityTable(limit.map(allEntities.take).getOrElse(allEntities), entitySchema, underlyingTask)
  }

  /** Transforms the entities that the given rule reads from the source. */
  private def transformedEntities(ruleInputSchema: EntitySchema,
                                  rule: TransformRule,
                                  requestedSchema: EntitySchema,
                                  limit: Option[Int])
                                 (implicit context: PluginContext, prefixes: Prefixes): CloseableIterator[Entity] = {
    val sourceEntities = source.retrieve(ruleInputSchema, limit).entities
    val taskContext = new ActivityMonitor[TransformReport](task.id, None)
    val reportBuilder = new TransformReportBuilder(task, taskContext)
    new TransformedEntities(task, sourceEntities, rule.label(), rule.execution(TaskContext.noInput()),
      requestedSchema, isRequestedSchema = true, abortIfErrorsOccur = false, report = reportBuilder).iterator
  }

  /**
    * The rules that generate the entities below a requested sub path, each with the schema it reads.
    * Target properties of a transform are a single hop, so nested entities come from nested object rules.
    *
    * @throws BadUserInputException If no rule generates the requested path at all.
    */
  private def rulesForSubPath(subPath: UntypedPath): Seq[(EntitySchema, TransformRule)] = {
    if(subPath.operators.isEmpty) {
      Seq((inputSchema, transformRule))
    } else {
      val transformSpec = task.data
      // Sub paths of the rule schemata are absolute, so the path of this source's own rule is prepended
      val basePath = transformSpec.ruleSchemata.find(_.transformRule.id == transformRule.id)
        .map(_.outputSchema.subPath).getOrElse(UntypedPath.empty)
      val targetPath = basePath ++ subPath
      // Only this source's own rule tree: a sibling rule may share the target path, but is not delivered
      val subtreeSchemata = transformSpec.ruleSchemataWithinRule(transformRule)
      val rules = subtreeSchemata.filter(_.outputSchema.subPath == targetPath)
      // A path generated as a value property holds no entities below it, which is not an error
      if(rules.isEmpty && !subtreeSchemata.exists(_.generatesValueAt(targetPath))) {
        throw new BadUserInputException(s"No rule of transform task '${task.id}' generates the requested path " +
          s"'${targetPath.normalizedSerialization}'.")
      }
      rules.map(schemata => (schemata.inputSchema, schemata.transformRule))
    }
  }

  /**
    * Retrieves a list of entities from this source.
    *
    * @param entitySchema The entity schema
    * @param entities     The URIs of the entities to be retrieved.
    * @return A Traversable over the entities. The evaluation of the Traversable may be non-strict.
    */
  override def retrieveByUri(entitySchema: EntitySchema, entities: Seq[Uri])
                            (implicit context: PluginContext): EntityHolder = {
    if(entities.isEmpty) {
      EmptyEntityTable(underlyingTask)
    } else {
      val entitySet = entities.toSet
      retrieve(entitySchema).filter(e => entitySet.contains(e.uri))
    }
  }

  /**
    * The dataset task underlying the Datset this source belongs to
    *
    * @return
    */
  override lazy val underlyingTask: Task[DatasetSpec[Dataset]] = source.underlyingTask
}
