package org.silkframework.workspace.activity.transform

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.must.Matchers
import org.silkframework.config.{CustomTask, PlainTask}
import org.silkframework.dataset.operations.GetProjectFilesOperator
import org.silkframework.dataset.{DatasetSpec, MockDataset, MockDatasetExecutor}
import org.silkframework.dataset.DatasetSpec.GenericDatasetSpec
import org.silkframework.runtime.validation.BadUserInputException
import org.silkframework.workspace.WorkspaceFactory
import org.silkframework.workspace.exceptions.TaskNotFoundException
import org.silkframework.runtime.plugin.PluginRegistry
import org.silkframework.entity.EntitySchema
import org.silkframework.entity.paths.{ForwardOperator, UntypedPath}
import org.silkframework.rule._
import org.silkframework.runtime.activity.TestUserContextTrait
import org.silkframework.util.Uri
import org.silkframework.workspace.TestWorkspaceProviderTestTrait
import org.silkframework.workspace.activity.transform.ResolvedTransformInput.StaticSchemaInput
import org.silkframework.workspace.activity.transform.TransformTaskUtils._

/**
  * Tests the resolution of transform inputs that are transform tasks themselves.
  */
class ResolvedTransformInputTest extends AnyFlatSpec with Matchers with TestWorkspaceProviderTestTrait with TestUserContextTrait {

  behavior of "ResolvedTransformInput"

  override def workspaceProviderId: String = "inMemoryWorkspaceProvider"

  // MockDataset only provides data access if its executor is registered
  PluginRegistry.unregisterPlugin(classOf[MockDatasetExecutor])
  PluginRegistry.registerPlugin(classOf[MockDatasetExecutor])

  private val sourceType = "urn:source:Person"
  private val rootType = "urn:target:Person"
  private val nestedType = "urn:target:Address"

  it should "resolve the schema of an upstream transform that reads a typed source" in {
    val project = retrieveOrCreateProject("typedUpstreamTest")
    project.addTask("upstream", upstreamTransform)
    project.addTask("downstream", TransformSpec(selection = DatasetSelection("upstream")))

    // The source type of the upstream transform must not be matched against its target types
    val input = project.task[TransformSpec]("downstream").resolveInput
    input mustBe a[StaticSchemaInput]
    val schema = input.asInstanceOf[StaticSchemaInput].schema
    schema.typeUri mustBe Uri(rootType)
    targetProperties(schema) must contain("urn:target:name")
  }

  it should "resolve the schema of the upstream rule that generates the selected type" in {
    val project = retrieveOrCreateProject("nestedUpstreamTest")
    project.addTask("upstream", upstreamTransform)
    project.addTask("downstream", TransformSpec(selection = DatasetSelection("upstream", Uri(nestedType))))

    val input = project.task[TransformSpec]("downstream").resolveInput
    val schema = input.asInstanceOf[StaticSchemaInput].schema
    schema.typeUri mustBe Uri(nestedType)
    targetProperties(schema) must contain("urn:target:city")
    targetProperties(schema) must not contain "urn:target:name"
  }

  it should "fall back to the primary output type if the selected type is not generated by the upstream transform" in {
    val project = retrieveOrCreateProject("staleTypeUpstreamTest")
    project.addTask("upstream", upstreamTransform)
    // A type that is left over from a previous input dataset, i.e. no upstream rule generates it
    project.addTask("downstream", TransformSpec(selection = DatasetSelection("upstream", Uri(sourceType))))

    val input = project.task[TransformSpec]("downstream").resolveInput
    val staticInput = input.asInstanceOf[StaticSchemaInput]
    staticInput.typeUri mustBe Uri("")
    staticInput.schema.typeUri mustBe Uri(rootType)
    targetProperties(staticInput.schema) must contain("urn:target:name")
  }

  it should "provide a data source through a chain of transform tasks" in {
    val project = retrieveOrCreateProject("transformChainTest")
    project.addTask[GenericDatasetSpec]("sourceDataset", DatasetSpec(MockDataset()))
    project.addTask("upstream", upstreamTransform)
    project.addTask("middle", TransformSpec(
      selection = DatasetSelection("upstream"),
      mappingRule = singleRule("middleName", UntypedPath.parse("<urn:target:name>"))
    ))
    project.addTask("downstream", TransformSpec(selection = DatasetSelection("middle")))

    // The chain of transform tasks is followed until the dataset that provides the entities
    project.task[TransformSpec]("middle").resolveInput.dataSourceOption mustBe defined
    project.task[TransformSpec]("downstream").resolveInput.dataSourceOption mustBe defined
  }

  it should "report a circular chain of transform tasks instead of recursing" in {
    val projectId = "circularInputTest"
    val project = retrieveOrCreateProject(projectId)
    project.addTask("first", TransformSpec(selection = DatasetSelection("second"), mappingRule = singleRule("firstName", path("name"))))
    project.addTask("second", TransformSpec(selection = DatasetSelection("sourceDataset"), mappingRule = singleRule("secondName", path("name"))))
    // Adding a circular input is rejected, but loading one is not, so the cycle is written straight to the provider
    // and the workspace is reloaded - the way an imported or restored project introduces one.
    workspaceProvider.putTask(projectId,
      PlainTask("second", TransformSpec(selection = DatasetSelection("first"), mappingRule = singleRule("secondName", path("name")))),
      project.resources)
    WorkspaceFactory().workspace.reload()

    val reloaded = WorkspaceFactory().workspace.project(projectId).task[TransformSpec]("first")
    // The chain starts at the input of 'first', so the cycle is reported from there
    val exception = the[BadUserInputException] thrownBy reloaded.resolveInput.dataSourceOption
    exception.getMessage must include("second -> first -> second")
  }

  it should "not provide a data source if the chain of transform tasks does not end in a dataset" in {
    val project = retrieveOrCreateProject("openChainTest")
    project.addTask[CustomTask]("filesTask", GetProjectFilesOperator(filesRegex = ".*"))
    project.addTask("head", TransformSpec(selection = DatasetSelection("filesTask"), mappingRule = singleRule("path", path("filePath"))))
    project.addTask("tail", TransformSpec(selection = DatasetSelection("head")))

    // A fixed output schema provides a schema but no data, which is not an error
    project.task[TransformSpec]("tail").resolveInput.dataSourceOption mustBe empty
  }

  it should "report a missing task in the chain rather than reporting that there is no data" in {
    val project = retrieveOrCreateProject("brokenChainTest")
    project.addTask("head", upstreamTransform) // Reads 'sourceDataset', which does not exist here
    project.addTask("tail", TransformSpec(selection = DatasetSelection("head")))

    a[TaskNotFoundException] must be thrownBy project.task[TransformSpec]("tail").resolveInput.dataSourceOption
  }

  it should "expose the nested rules of an upstream transform" in {
    val project = retrieveOrCreateProject("nestedSchemataTest")
    project.addTask("upstream", upstreamTransform)
    project.addTask("downstream", TransformSpec(selection = DatasetSelection("upstream")))
    val input = project.task[TransformSpec]("downstream").resolveInput

    // The root rule and the nested address rule, the latter addressed by the sub path that generates it
    val schemata = input.asInstanceOf[StaticSchemaInput].nestedSchemata
    schemata.map(_.subPath) mustBe Seq(UntypedPath.empty, path("urn:target:address"))
    targetProperties(schemata.last) must contain("urn:target:city")
    // Nested object rules make the input hierarchical, so generated object mappings keep their source path
    input.characteristics.supportedPathExpressions.multiHopPaths mustBe true
  }

  it should "report an upstream transform without nested object rules as flat" in {
    val project = retrieveOrCreateProject("flatUpstreamTest")
    project.addTask("upstream", TransformSpec(
      selection = DatasetSelection("sourceDataset", Uri(sourceType)),
      mappingRule = singleRule("flatName", path("name"))
    ))
    project.addTask("downstream", TransformSpec(selection = DatasetSelection("upstream")))

    project.task[TransformSpec]("downstream").resolveInput.characteristics.supportedPathExpressions.multiHopPaths mustBe false
  }

  it should "report whether the input schema contains multi-hop paths" in {
    def schemaOf(paths: UntypedPath*): EntitySchema = {
      EntitySchema(Uri(rootType), paths.map(_.asStringTypedPath).toIndexedSeq)
    }
    val flat = StaticSchemaInput(schemaOf(path("name")))
    val nested = StaticSchemaInput(schemaOf(path("name"), UntypedPath(List(ForwardOperator("address"), ForwardOperator("city")))))

    flat.characteristics.supportedPathExpressions.multiHopPaths mustBe false
    nested.characteristics.supportedPathExpressions.multiHopPaths mustBe true
  }

  /** An upstream transform that reads a typed source and maps it to a root and a nested object rule. */
  private def upstreamTransform: TransformSpec = {
    TransformSpec(
      selection = DatasetSelection("sourceDataset", Uri(sourceType)),
      mappingRule = RootMappingRule(MappingRules(
        typeRules = Seq(TypeMapping(id = "rootType", typeUri = rootType)),
        propertyRules = Seq(
          DirectMapping(id = "name", sourcePath = path("name"), mappingTarget = MappingTarget("urn:target:name")),
          ObjectMapping(
            id = "address",
            sourcePath = path("address"),
            target = Some(MappingTarget("urn:target:address")),
            rules = MappingRules(
              typeRules = Seq(TypeMapping(id = "addressType", typeUri = nestedType)),
              propertyRules = Seq(DirectMapping(id = "city", sourcePath = path("city"), mappingTarget = MappingTarget("urn:target:city")))
            )
          )
        )
      ))
    )
  }

  /** A root rule with a single direct mapping. */
  private def singleRule(id: String, sourcePath: UntypedPath): RootMappingRule = {
    RootMappingRule(MappingRules(propertyRules = Seq(
      DirectMapping(id = id, sourcePath = sourcePath, mappingTarget = MappingTarget(s"urn:target:$id"))
    )))
  }

  private def path(property: String): UntypedPath = UntypedPath(List(ForwardOperator(property)))

  private def targetProperties(schema: EntitySchema): Set[String] = {
    schema.typedPaths.flatMap(_.operators.collect { case ForwardOperator(property) => property.uri }).toSet
  }
}
