package org.silkframework.execution

import org.silkframework.util.Identifier

/**
  * An execution type.
  */
trait ExecutionType {

  /** The type of data that is generated by each task. */
  type DataType <: EntityHolder

  /**
   * Set if the execution happens within a workflow.
   */
  def workflowId: Option[Identifier]

}
