package org.silkframework.execution

import org.silkframework.execution.EntityHolder

/**
  * An execution type.
  */
trait ExecutionType {

  /** The type of data that is generated by each task. */
  type DataType <: EntityHolder

}
