package org.silkframework.execution

import org.silkframework.execution.local.{LocalEntities, LocalExecution}

/**
  * An execution type.
  */
trait ExecutionType {

  /** The type of data that is generated by each task. */
  type DataType <: EntityHolder

}

/**
  * The concrete entity holder type for a specific execution
  * @tparam ExecType
  */
type EntityType[ExecType <: ExecutionType] <: EntityHolder = ExecType match
  case _ => LocalEntities
