package org.silkframework.rule.plugins.transformer.combine

import org.silkframework.rule.test.TransformerTest

class ConcatMultipleValuesTransformerTest extends TransformerTest[ConcatMultipleValuesTransformer]
