package org.silkframework.rule.plugins.transformer.sparql

import org.silkframework.rule.test.TransformerTest

class EscapeMultilineLiteralTransformerTest extends TransformerTest[EscapeMultilineLiteralTransformer]