package org.silkframework.rule.execution.local

import org.silkframework.runtime.validation.ValidationException

/**
  * Thrown if multiple values/entities have been generated by a rule that only allows single value/entity.
  */
class MultipleValuesException(message: String)
  extends ValidationException(message)
