const activities = [
    {
        id: "GlobalUriPatternCache",
        label: "Global URI pattern cache",
        parentType: "global",
        isCacheActivity: false,
    },
    {
        id: "GlobalVocabularyCache",
        label: "Global vocabulary cache",
        parentType: "global",
        isCacheActivity: true,
    },
    {
        id: "GlobalVocabularySynonymCache",
        label: "Global vocabulary synonym cache",
        parentType: "global",
        isCacheActivity: true,
    },
    {
        id: "ActiveLearning",
        label: "Active learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatibelzuS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatibel zu S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "EvaluateLinking",
        label: "Evaluate linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatibelzuS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatibel zu S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ExecuteLinking",
        label: "Execute linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatibelzuS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatibel zu S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "LinkingPathsCache",
        label: "Linking paths cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatibelzuS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatibel zu S210",
        parentType: "linking",
        isCacheActivity: true,
    },
    {
        id: "ReferenceEntitiesCache",
        label: "Reference entities cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatibelzuS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatibel zu S210",
        parentType: "linking",
        isCacheActivity: true,
    },
    {
        id: "SupervisedLearning",
        label: "Supervised learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatibelzuS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatibel zu S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ActiveLearning",
        label: "Active learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatiblemitS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatible mit S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "EvaluateLinking",
        label: "Evaluate linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatiblemitS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatible mit S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ExecuteLinking",
        label: "Execute linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatiblemitS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatible mit S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "LinkingPathsCache",
        label: "Linking paths cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatiblemitS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatible mit S210",
        parentType: "linking",
        isCacheActivity: true,
    },
    {
        id: "ReferenceEntitiesCache",
        label: "Reference entities cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatiblemitS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatible mit S210",
        parentType: "linking",
        isCacheActivity: true,
    },
    {
        id: "SupervisedLearning",
        label: "Supervised learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2kompatiblemitS210-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2 kompatible mit S210",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ActiveLearning",
        label: "Active learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2_Test-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2_Test",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "EvaluateLinking",
        label: "Evaluate linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2_Test-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2_Test",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ExecuteLinking",
        label: "Execute linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2_Test-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2_Test",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "LinkingPathsCache",
        label: "Linking paths cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2_Test-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2_Test",
        parentType: "linking",
        isCacheActivity: true,
    },
    {
        id: "ReferenceEntitiesCache",
        label: "Reference entities cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2_Test-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2_Test",
        parentType: "linking",
        isCacheActivity: true,
    },
    {
        id: "SupervisedLearning",
        label: "Supervised learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-1FK2_Test-Istkompatibelzu-Basisfelder",
        taskLabel: "1FK2_Test",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ActiveLearning",
        label: "Active learning",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-3AC-V20AehnlicherArtikel-AehnlicherArtikel-Basisfelder",
        taskLabel: "3AC-V20 Ähnlicher Artikel",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "EvaluateLinking",
        label: "Evaluate linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-3AC-V20AehnlicherArtikel-AehnlicherArtikel-Basisfelder",
        taskLabel: "3AC-V20 Ähnlicher Artikel",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "ExecuteLinking",
        label: "Execute linking",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-3AC-V20AehnlicherArtikel-AehnlicherArtikel-Basisfelder",
        taskLabel: "3AC-V20 Ähnlicher Artikel",
        parentType: "linking",
        isCacheActivity: false,
    },
    {
        id: "LinkingPathsCache",
        label: "Linking paths cache",
        project: "cmem",
        projectLabel: "cmem",
        task: "LinkingTask-3AC-V20AehnlicherArtikel-AehnlicherArtikel-Basisfelder",
        taskLabel: "3AC-V20 Ähnlicher Artikel",
        parentType: "linking",
        isCacheActivity: true,
    },
];

const facets = [
    {
        id: "status",
        label: "Status",
        description: "The activity status.",
        type: "keyword",
        values: [
            {
                id: "Idle",
                label: "Idle",
                count: 7614,
            },
            {
                id: "Finished",
                label: "Finished",
                count: 4558,
            },
        ],
    },
    {
        id: "activityType",
        label: "Activity type",
        description: "Activity type (either cache or non-cache activity).",
        type: "keyword",
        values: [
            {
                id: "non-cache",
                label: "Non-Cache activity",
                count: 7630,
            },
            {
                id: "cache",
                label: "Cache activity",
                count: 4542,
            },
        ],
    },
];

const testData = {
    activities,
    facets,
};

export default testData;
