package org.silkframework.execution.local

import org.silkframework.config.{Task, TaskSpec}
import org.silkframework.entity.{Entity, EntitySchema}

case class GenericEntityTable(entities: Traversable[Entity], entitySchema: EntitySchema, task: Task[TaskSpec]) extends LocalEntities {
  /**
    * The task that generated this table.
    * If the entity table has been generated by a workflow this is a copy of the actual task that has been executed.
    */
  override def taskOption: Option[Task[TaskSpec]] = Some(task)
}
